trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- task: AzureKeyVault@2
  displayName: Get the secrets
  inputs:
    azureSubscription: 'KVTest'
    KeyVaultName: 'new-test-marv'
    SecretsFilter: '*'
    RunAsPreJob: false

- task: CmdLine@2
  displayName: Copy the secrets to a file
  inputs:
    script: 'echo $(your-secret) > secret.txt'

- task: CopyFiles@2
  displayName: create the folder
  inputs:
    Contents: secret.txt
    targetFolder: '$(Build.ArtifactStagingDirectory)'

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'drop'
    publishLocation: 'Container'