trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
  - 
- task: AzureKeyVault@2
  inputs:
    azureSubscription: 'KVTest'
    KeyVaultName: 'new-test-marv'
    SecretsFilter: '*'
    RunAsPreJob: false
